### ISSUE TITLE
[kube-prometheus-stack] Prometheus Agent support (storage.tsdb.path flag disablement)

### ISSUE THREAD

**Issue by rmorilha** [prometheus-community/helm-charts#2506]
### Is your feature request related to a problem ?

With the support for Prometheus Agent in the values file (`prometheusSpec.enableFeatures[agent]`), some configurations must be disabled.

More specifically:
- `--storage.tsdb.retention.time`   --> Able to disable this in the kube-prometheus-stack values.yaml param `prometheusSpec.retention`
- `--storage.tsdb.wal-compression`   --> Able to disable this in the kube-prometheus-stack values.yaml param `prometheusSpec.walCompression`
- `--storage.tsdb.path`  --> UNABLE to disable/configure this through kube-prometheus-stack values.yaml
   - Already tried to remove the storage spec itself.
   - Already tried to remove manually from statefulset (operator adjusts it back)

**Current kube-prometheus-stack chart version**: 40.1.2
**Current prometheus version**:  v2.38.0
**Current prometheus operator version**: v0.59.1

**Below follows the log from prometheus pod:**
```bash
ts=2022-09-29T17:11:14.618Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
The following flag(s) can not be used in agent mode: ["--storage.tsdb.retention.time" "--storage.tsdb.path" "--storage.tsdb.wal-compression"]
```

### Describe the solution you'd like.

As far as I could see in the code, the Prometheus chart templates has openness for the addition of a values parameter to support this disablement/configuration path...more specifically in the files:
- sts.yaml
   - Under filepath `prometheus/templates/server/sts.yaml`
   - On lines 107 -> 110
- deploy.yaml
   - Under filepath `prometheus/templates/server/deploy.yaml`
   - On lines 103 -> 107

Below follows the code of the files aforementioned:

**sts.yaml:**
```yaml
          {{- if .Values.server.storagePath }}
            - --storage.tsdb.path={{ .Values.server.storagePath }}
          {{- else }}
            - --storage.tsdb.path={{ .Values.server.persistentVolume.mountPath }}
          {{- end }}
```

**deploy.yaml:**
```yaml
            {{- if .Values.server.storagePath }}
            - --storage.tsdb.path={{ .Values.server.storagePath }}
            {{- else }}
            - --storage.tsdb.path={{ .Values.server.persistentVolume.mountPath }}
            {{- end }}
```

Currently, these files only contains the enforcement of the `--storage.tsdb.path` argument, either through `server.storagePath` or  `server.persistentVolume.mountPath`, but no option to **not** have it (again, due to Prometheus agent support feature enabled since 2.32 version of prometheus).

I have never contributed in an open-source project before and I also have zero experience with operators, specially Prometheus.
Can someone that is more versed on the prometheus open-source repository and code, implement the disablement of the above-mentioned `storage.tsdb.path` and allow it to be configurable all the way until kube-prometheus-stack values file ?

### Describe alternatives you've considered.

- Already tried to remove the storage spec itself.
- Already tried to remove manually from statefulset (operator adjusts it back)

**Comment by rmorilha** [comment]
#825 issue relates to this one

**Comment by tomrijnbeek** [comment]
I have been digging into this myself recently, because I am trying to deploy the Prometheus agent using this Helm chart as well. The `kube-prometheus-stack` doesn't use the use the `prometheus` chart under the hood, so I am not sure if the solution you propose is going to work. The `kube-prometheus-stack` instead uses Prometheus Operator to deploy Prometheus instead.

I have been able to get past most of the obstacles here by using the following values:

```yaml
      prometheusOperator:
        enabled: true
      prometheus:
        enabled: true

        prometheusSpec:
          enableFeatures:
            - agent
          remoteWrite:
            - url: "prometheus.example:9090/api/v1/push"
          containers:
            - name: prometheus
              args:
              - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
              - '--storage.agent.path=/prometheus'
              - '--enable-feature=agent'
              - '--web.enable-lifecycle'

      alertmanager:
        enabled: false
      grafana:
        enabled: false
      pushgateway:
        enabled: false
      defaultRules:
        create: false
```

This was inspired by [this comment](https://github.com/prometheus-operator/prometheus-operator/issues/3989#issuecomment-974137486) on the Prometheus Operator repository. The only problem is that the configuration still fails with the following error in the logs:

```
Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="field alerting is not allowed in agent mode
```

As of prometheus-operator/prometheus-operator#4417, if the `Prometheus` CR does not contain an `alerting` block in the spec, the `alerting` block in the config will not be written, but [as this comment mentions](https://github.com/prometheus-community/helm-charts/issues/1519#issuecomment-1118917359), the `alerting` block in the `Prometheus` CR is currently hardcoded in the Helm template for the `kube-prometheus-stack`.

I would argue that this issue is probably a duplicate of #1519.

As for what the fix should be: the `alerting` block in the `Prometheus` CR should probably be conditional based on whether any alerting-related config is specified. The question is whether this will be done, because the overall agreement appears to be that the Prometheus agent will be represented by a brand new CR, but it is unclear to me what the progress on implementation of that CR is. As a workaround, [this comment](https://github.com/prometheus-community/helm-charts/issues/1519#issuecomment-1190235633) proposes a way of deploying Prometheus in agent mode using just the `prometheus` chart. That means you may have to deploy other aspects of the `kube-prometheus-stack` manually (e.g. node exporter and kube stats), but that should at least help carry you over until a permanent solution for Prometheus agent deployment has been found.

**Comment by Cheshirez** [comment]
It's possible to proceed with `kube-prometheus-stack` and `kind: Prometheuses` custom resource to utilize both sharding and replicas, but require a patched `prometheus-operator`. 
https://github.com/prometheus-operator/prometheus-operator/pull/4482

It has disadvantages that you'll need to reapply patches to next versions and switch infra once the mentioned brand new CR appear, but it's already 10 months in the development and no ETA. So the question is rather how often you plan to update the operator.

**Comment by fenethtool** [comment]
Thanks to the merge of the PR created by @jkroepke, the error caused by the alerting field appears to have been resolved. (To try this, you need to get the latest contents of prometheus-operator, with prometheusOperator.prometheusConfigReloader.image.tag as the main before the release).

However, I still get the following error.

```
ts=2022-11-05T12:33:13.291Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
ts=2022-11-05T12:33:13.301Z caller=main.go:455 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="field rule_files is not allowed in agent mode"
```

In the prometheus helm chart, the configuration file is defined as a configmap, so it is possible to control the `rule_files` block as [this comment](https://github.com/prometheus-community/helm-charts/issues/1519#issuecomment-1239048761), but in kube-prometheus-stack, it seems that these files are also generated via operator. At the moment, there appears to be no way to control this with valuefile. (I may have just missed it. If anyone knows, please let me know)

**Comment by jkroepke** [comment]
@fenethtool 

try to set ruleSelector to nil 

https://github.com/prometheus-operator/prometheus-operator/blob/5a23b12b3902995a3fee0b9588e2fb4cc8fa1ce8/pkg/prometheus/promcfg.go#L425-L434

**Comment by jkroepke** [comment]
If https://github.com/prometheus-community/helm-charts/pull/2648 is merged, I can run the Prometheus Agent with kube-prometheus-stack..


```yaml
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: http://cortex-nginx.infra-cortex.svc/api/v1/push
    remoteWriteDashboards: true
    # https://github.com/prometheus-operator/prometheus-operator/blob/5a23b12b3902995a3fee0b9588e2fb4cc8fa1ce8/pkg/prometheus/promcfg.go#L425-L434      
    ruleSelector: ~
    ruleSelectorNilUsesHelmValues: false
    enableFeatures:
      - agent
    # https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1277362029
    containers:
    - name: prometheus
      args:
        - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
        - '--storage.agent.path=/prometheus'
        - '--enable-feature=agent'
        - '--web.enable-lifecycle'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.external-url=http://kube-prometheus-stack-prometheus.infra-prometheus:9090'
        - '--web.route-prefix=/'
        - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'
```

**Comment by Sarang-Dharme-od** [comment]
Hello @jkroepke @rmorilha 

I am facing below issues, can you please help - 

1)After updating values.yaml with prometheusSpec.retention: "" & walCompression: false, prometheus statefulset still showing retention flag(10d/24h). How to get rid of retention & walCompression?

2)After upgrading kube-prometheus-stack helm chart, still getting below error -
  level=info msg="Experimental agent mode enabled." The following flag(s) can not be used in agent mode: ["--storage.tsdb.retention.time" "--storage.tsdb.path" "--storage.tsdb.wal-compression"]
  
Thanks in advance!

**Comment by Sarang-Dharme-od** [comment]
> Hi @Sarang-Dharme-od you have to override the prometheus container like above.

@jkroepke Would you mind elaborating bit more on how to override the Prometheus container? Do I need to replace prometheus.yaml template with your above mentioned code snippet (https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1304632868)? Please advise!

**Comment by jkroepke** [comment]
the code snippet above is a part of the values.yaml for the kube-prometheus-stack. It work after https://github.com/prometheus-community/helm-charts/pull/2648 is merged.

**Comment by Budgiebrain994** [comment]
I'm using a Helm postrenderer to manually `sed` the generated manifest and remove the `ruleSelector` field before the Helm manifest is applied. While it's not ideal, it is a valid workaround until your aforementioned PR is merged.
```
helm upgrade -f prometheus-operator-agent.yaml --repo 'https://prometheus-community.github.io/helm-charts' kube-prometheus-stack kube-prometheus-stack --post-renderer sed --post-renderer-args "-E" --post-renderer-args "s/  ruleSelector: {}//g"
```
I'm looking forward to when your PR is reviewed and approved 😄

**Comment by hoangphuocbk** [comment]
@jkroepke I updated the latest code and switched to agent mode. Thank for your help  :+1:

**Comment by pb-dod** [comment]
I ended up needing to use `defaultFlagsOverride` to work around this `The following flag(s) can not be used in agent mode: ["--storage.tsdb.path"]` issue while using agent mode (`--enable-feature=agent`):
```
server:
  persistentVolume:
    enabled: false
  replicaCount: 1
  # We're using defaultFlagsOverride because the chart will use --storage.tsdb.path if you don't,
  # and that's not allowed in agent mode. For more context, see:
  # https://github.com/prometheus-community/helm-charts/issues/825#issuecomment-1262624864
  defaultFlagsOverride:
    - --config.file=/etc/config/prometheus.yml
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --web.enable-lifecycle
    - --web.enable-remote-write-receiver
    - --enable-feature=agent
    - --storage.agent.retention.max-time=2h
```
