### ISSUE TITLE
[kube-prometheus-stack] Prometheus pods and alertmanager pods terminating continuously

### ISSUE THREAD

**Issue by kirankothakota1982** [prometheus-community/helm-charts#3117]
my Kubernetes version is 1.25.5, prometheus helm chart version I am using is 45.7.0. Using these configuration deployed application from ArgoCD. v2.4.6+A.  Both alertmanager and prometheus pods are getting terminated. 
failing to mount volumes. Please find below messages.

17m         Warning   FailedMount              pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Unable to attach or mount volumes: unmounted volumes=[prometheus-kube-prometheus-kube-prome-prometheus-db], unattached volumes=[config-out prometheus-kube-prometheus-kube-prome-prometheus-rulefiles-0 kube-api-access-zw5w5 tls-assets prometheus-kube-prometheus-kube-prome-prometheus-db web-config config]: timed out waiting for the condition

kubectl get pods -n monitoring |grep -i prome
alertmanager-alertmanager-kube-promethe-alertmanager-0            0/2     Terminating   0          14s
blackbox-dns-prod-prometheus-blackbox-exporter-56fff66f99-vbscf   1/1     Running       0          34d
blackbox-jenkins-gp-prometheus-blackbox-exporter-84d56f6c5q8ngg   1/1     Running       0          34d
blackbox-vault-hub-prometheus-blackbox-exporter-7494677f78wz6np   1/1     Running       0          34d
kube-prometheus-kube-prome-operator-fcccdf5c8-v94vq               1/1     Running       0          3h42m
kube-prometheus-kube-state-metrics-85bf8d7c6c-vgjsb               1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-4frqn                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-4r6bg                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-gbv86                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-kxr8d                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-m94hl                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-nwg7d                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-q9cnh                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-rdf2x                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-vh4xb                    1/1     Running       0          3h42m
kube-prometheus-prometheus-node-exporter-zljlc                    1/1     Running       0          3h42m
prometheus-kube-prometheus-kube-prome-prometheus-0                0/2     Terminating   0          8s

Also adding event logs which I am getting.
57s         Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
57s         Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
54s         Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k
47s         Normal    Pulled                   pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0" already present on machine
47s         Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
46s         Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
44s         Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k
36s         Normal    Pulled                   pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.54.0" already present on machine
36s         Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
36s         Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
34s         Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k
26s         Normal    Pulled                   pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0" already present on machine
26s         Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
26s         Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
23s         Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k
16s         Normal    Pulled                   pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0" already present on machine
16s         Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
16s         Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
13s         Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k
6s          Normal    Pulled                   pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0" already present on machine
6s          Normal    Created                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Created container init-config-reloader
6s          Normal    Started                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Started container init-config-reloader
6s          Normal    Killing                  pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Stopping container init-config-reloader
4s          Normal    Scheduled                pod/prometheus-kube-prometheus-kube-prome-prometheus-0   Successfully assigned monitoring/prometheus-kube-prometheus-kube-prome-prometheus-0 to aks-gp0-96055053-vmss00000k

**Comment by srujansagi** [comment]
I do see the similar behavior from last two days where alert-manager and Prometheus pods are in terminating state.

I see this error but unsure where it is coming from as i'm using latest chart.

`level=info ts=2023-03-13T15:46:10.443767801Z caller=operator.go:790 component=alertmanageroperator key=prometheus/prometheus-stack-kube-prom-alertmanager msg="update alertmanager status"
level=error ts=2023-03-13T15:46:10.464811449Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"prometheus/prometheus-stack-kube-prom-alertmanager\" failed: failed to update status subresource: Operation cannot be fulfilled on alertmanagers.monitoring.coreos.com \"prometheus-stack-kube-prom-alertmanager\": the object has been modified; please apply your changes to the latest version and try again"`

**Comment by kirankothakota1982** [comment]
anyone having any idea why this issue is coming? What is the solution for this?

**Comment by kirankothakota1982** [comment]
I am also getting this message in my logs for alertmanager as well.  Though I am using it from helm chats.
 kubectl logs alertmanager-alertmanager-kube-promethe-alertmanager-0 -n monitoring
ts=2023-03-16T14:43:59.784Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
ts=2023-03-16T14:43:59.784Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe866dd5717, date=20221222-14:51:36)"
ts=2023-03-16T14:43:59.822Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-03-16T14:43:59.822Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="open /etc/alertmanager/config_out/alertmanager.env.yaml: no such file or directory"

**Comment by DigiDr** [comment]
We're also seeing this. @kirankothakota1982 did you find a solution?

**Comment by zeritti** [comment]
> I do see the similar behavior from last two days where alert-manager and Prometheus pods are in terminating state.
> 
> I see this error but unsure where it is coming from as i'm using latest chart.
> 
> `level=info ts=2023-03-13T15:46:10.443767801Z caller=operator.go:790 component=alertmanageroperator key=prometheus/prometheus-stack-kube-prom-alertmanager msg="update alertmanager status" level=error ts=2023-03-13T15:46:10.464811449Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"prometheus/prometheus-stack-kube-prom-alertmanager\" failed: failed to update status subresource: Operation cannot be fulfilled on alertmanagers.monitoring.coreos.com \"prometheus-stack-kube-prom-alertmanager\": the object has been modified; please apply your changes to the latest version and try again"`

This error was very likely caused by missing authorization in Prometheus Operator's cluster role on `alertmanagers/status`. Was fixed in 45.1.1.

**Comment by dominch** [comment]
I just have same thing on 45.27.1 probably #3148 is also this particular problem. 
Are there any extra steps when I upgrade this chart? I jumped from 44.x (and something similar was there)  

Also - even if something is seriously wrong on upgrade etc - stack should not restart as fast as possible eating cpu with endless loop. Maybe in case of error it should have some reasonable delay for that so it's not dying as fast as possible.. ;) 
Also restart counter on k8s is not working for this case. Pod is recreated over and over again but You may not notice that. Monitoring stack is working.

**Comment by holmesb** [comment]
Occurring in 45.27.2 too. The prometheus-0 pod and alertmanager loop straight from pending to terminating. Restarts = 0. Only occurs for upgrades. Fresh install on a new cluster works fine. But uninstall\reinstall fails. Am upgrading to the right CRD version: v0.65.1. To reproduce:

```
helm upgrade --install --namespace monitoring --version 45.7.1 prometheus-stack prometheus-community/kube-prometheus-stack
<observe pods successfully started>
curl -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.65.1/bundle.yaml | kubectl apply --server-side --force-conflicts -f -
helm upgrade --install --namespace monitoring --version 45.27.2 prometheus-stack prometheus-community/kube-prometheus-stack
```

**Comment by kjaleshire** [comment]
Same thing on k3s `v1.27.1+k3s1` with chart `45.29.0`.

**Comment by dominch** [comment]
I also decided to remove whole chart (constantly restarting and not working with this issue), after re-installation problem still occurs. I also confirmed that it is ok on fresh cluster, so probably still something is not removed. Had anybody time to debug this already?

**Comment by kirankothakota1982** [comment]
> We're also seeing this. @kirankothakota1982 did you find a solution?

No, did also trails, still not found any solution. Let me know if you find any?

**Comment by kirankothakota1982** [comment]
> alertmanagers/status

Is this fixed, if so can you elaborate little bit more?

**Comment by NLSKHA1** [comment]
Check once if there are previous versions of operator present in any namespace of your cluster - stopping the service in your namespace from coming up.
If multiple prometheus operator is monitoring same service then one of the operator needs to be removed.
I had the issue of default namespace having extra prometheus operator and its respective services - getting rid of which got it working

**Comment by kirankothakota1982** [comment]
after few checks I found some how prometheus operator pod created in default namespace. Where as per Prometheus policy in a single cluster there shouldn't be two prometheus operators. So, I have deleted deployment of prometheus operator of default one. Later issue resolved for me.  Thanks.

**Comment by dominch** [comment]
I also had those issues and eventually I needed to delete everything I could find regarding prometheus  and also plugged off one arm node. Something have helped and now it's working. I also had one pod in default namespace, but I'm quite sure it's not that what caused problems.

**Comment by pawan-protiviti** [comment]
I need to create 2 Prometheus Operator pods, one in the existing namespace i.e. monitor, which is running right now & another is in monitor-2 namespace. 

So , when trying to deploy a new release name like kube-promtheus-stack-2 and namespace monitor-2 then seems Prometheus operator is putting both old and new Prometheus and alertmanager pods into a terminating loop. pls help to get it resolved.
